import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";
import BuilderToolbar from "@/components/builder/builder-toolbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shadcn Sidebar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="p-5 space-y-2.5">
          <BuilderToolbar />
          <div className="bg-white border p-3 rounded-lg drop-shadow-lg h-[calc(100vh-100px)] overflow-hidden">
            {children}
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
